#!/usr/bin/env bash
# This is a throw-away script for finding a dicom image in a DTI series of interest. Delete this script.
echo /hpf/largeprojects/smiller/images/prem_ubc/prem_ubc_dicom/"$(pwd | rev | cut -d / -f 2-3 | rev)"/0003.dcm
