#!/usr/bin/env python

# Input a dicom file path and a directory containing many dicom files. Check if any of the files in the specified directory are the same as the specified dicom file.

import os, sys
import pydicom as pd
import filecmp

dcmpath1 = str(sys.argv[1]) # path of dicom file to search for a match of
dcmdir2 = str(sys.argv[2])  # directory to look for a match in

dcm1 = pd.dcmread(dcmpath1)
dcm_pix1 = dcm1.PixelData

match_found = False
for root, directories, filenames in os.walk(dcmdir2):
    for filename in filenames:
        dcmpath2 = os.path.join(root,filename)
        dcm2 = pd.dcmread(dcmpath2)
        dcm_pix2 = dcm2.PixelData
        if filecmp.cmp(dcmpath1, dcmpath2):
            print "Exact copies:"
            print dcmpath1
            print dcmpath2
            print
            match_found = True
        elif (dcm_pix1 == dcm_pix2):
            print "Same pixel data:"
            print dcmpath1
            print dcmpath2
            print
            match_found = True

if (not match_found):
    print "Did not find copy of image:"
    print dcmpath1
    print "in"
    print dcmdir2
