#!/usr/bin/env python

# Check whether the header and pixel data differ between two dicom files.

import os, sys
import pydicom as pd
import filecmp # use to check if the files are the same

dcmpath1 = str(sys.argv[1])
dcmpath2 = str(sys.argv[2])

# dcm1 = pd.dcmread(dcmpath1)
# dcm2 = pd.dcmread(dcmpath2)

try:
    dcm_pix1 = pd.dcmread(dcmpath1).PixelData
    dcm_pix2 = pd.dcmread(dcmpath2).PixelData
    pix_eq = dcm_pix1 == dcm_pix2
except AttributeError:
    pix_eq = None

print "Pixel data equal: "+(str(pix_eq) if pix_eq != None else "Pixel data not found")
print "Files equal     : "+str(filecmp.cmp(dcmpath1, dcmpath2))
